name: Deploy to Firebase Hosting on push to Main
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - id: config-repo
        name: Pre config - 🧰 Checkout repository
        uses: actions/checkout@v3
      - id: config-node
        name: Pre config - 🧰 Set up node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: set-firebase-config
        name: Pre config - 🧰 Setting Firebase configurations
        run: |
          npm install -g firebase-tools
          firebase experiments:enable webframeworks
      - id: project-dependencies-installantion
        name: Installing and building project 📦
        run: |
          cd app
          yarn
          export NEXT_PUBLIC_THE_CHALLENGER_API_EVENT_ID=${{secrets.NEXT_PUBLIC_THE_CHALLENGER_API_EVENT_ID}}
          export NEXT_PUBLIC_API_KEY=${{secrets.NEXT_PUBLIC_API_KEY}}
          export NEXT_PUBLIC_AUTH_DOMAIN=${{secrets.NEXT_PUBLIC_AUTH_DOMAIN}}
          export NEXT_PUBLIC_PROJECT_ID=${{secrets.NEXT_PUBLIC_PROJECT_ID}}
          export NEXT_PUBLIC_STORAGE_BUCKET=${{secrets.NEXT_PUBLIC_STORAGE_BUCKET}}
          export NEXT_PUBLIC_MESSAGING_SENDER_ID=${{secrets.NEXT_PUBLIC_MESSAGING_SENDER_ID}}
          export NEXT_PUBLIC_APP_ID=${{secrets.NEXT_PUBLIC_APP_ID}}
          export NEXT_PUBLIC_MEASUREMENT_ID=${{secrets.NEXT_PUBLIC_MEASUREMENT_ID}}
          firebase use --token "${{secrets.FIREBASE_DEPLOYMENT_TOKEN}}" ${{secrets.NEXT_PUBLIC_PROJECT_ID}}
          firebase deploy --token "${{secrets.FIREBASE_DEPLOYMENT_TOKEN}}"
